import '../config/env.js';
import { connectDB } from '../config/db.js';
import Product from '../models/Product.js';
import User from '../models/User.js';


const products = [
  // --- ELECTRONICS (6) ---
  {
    name: 'iPhone 15 Pro Max (256GB - Titanium)',
    category: 'Electronics',
    price: 134900,
    originalPrice: 159900,
    discountedPrice: 134900,
    discountPercentage: 16,
    rating: 4.9,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    description: 'Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
    specs: ['A17 Pro chip with 6-core GPU', '6.7-inch Super Retina XDR OLED', '48MP Main Camera with 5x Optical Zoom', 'Titanium design with Ceramic Shield'],
    isTrending: true,
    isFeatured: true,
    stock: 25,
    badge: 'Top Rated',
    colors: ['#3b3c3e', '#e2e4e1', '#2f343b']
  },
  {
    name: 'Samsung Galaxy S24 Ultra (512GB)',
    category: 'Electronics',
    price: 109999,
    originalPrice: 129999,
    discountedPrice: 109999,
    discountPercentage: 15,
    rating: 4.8,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity, and possibility.',
    specs: ['Snapdragon 8 Gen 3 for Galaxy', '200MP Main Sensor + Galaxy AI', 'Built-in S Pen Stylus', '6.8" Dynamic AMOLED 2X 120Hz'],
    isTrending: true,
    isFeatured: true,
    stock: 18,
    badge: 'Best Seller',
    colors: ['#48494b', '#cfd4db', '#d9c5ab']
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    category: 'Electronics',
    price: 24900,
    originalPrice: 34900,
    discountedPrice: 24900,
    discountPercentage: 28,
    rating: 4.9,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Industry-leading noise canceling with two processors and 8 microphones for unprecedented sound quality and crystal-clear hands-free calling.',
    specs: ['30-hour battery life with quick charge', 'Custom 30mm driver unit', 'Speak-to-Chat & Multipoint Connection', 'Ultra-comfortable lightweight design'],
    isTrending: true,
    isFeatured: true,
    stock: 40,
    badge: 'Hot Deal',
    colors: ['#111111', '#e4e2dd']
  },
  {
    name: 'Apple Watch Series 9 GPS (45mm)',
    category: 'Electronics',
    price: 34900,
    originalPrice: 41900,
    discountedPrice: 34900,
    discountPercentage: 16,
    rating: 4.9,
    reviewCount: 388,
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    description: 'S9 SiP enables a super-bright display and a magical new way to quickly and easily interact with your Apple Watch without touching the screen.',
    specs: ['Always-On Retina Display (up to 2000 nits)', 'Double Tap gesture control', 'ECG app & Blood Oxygen tracking', 'Water resistant to 50 meters'],
    isTrending: true,
    isFeatured: true,
    stock: 30,
    badge: 'Trending',
    colors: ['#0f172a', '#e2e8f0', '#b91c1c']
  },
  {
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 8999,
    originalPrice: 12999,
    discountedPrice: 8999,
    discountPercentage: 30,
    rating: 4.8,
    reviewCount: 615,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    description: 'Louder, more powerful sound. The 2-way speaker system of JBL Flip 6 is engineered to deliver crisp, clear, and punchy audio with deep bass response.',
    specs: ['IP67 Waterproof & Dustproof', '12 Hours of Playtime per charge', 'PartyBoost pairing feature', 'Bold design with standing orientation'],
    isTrending: true,
    isFeatured: true,
    stock: 50,
    badge: 'Best Seller',
    colors: ['#dc2626', '#0f172a', '#0284c7']
  },
  {
    name: 'Keychron K2 Wireless Mechanical Keyboard',
    category: 'Electronics',
    price: 7999,
    originalPrice: 9999,
    discountedPrice: 7999,
    discountPercentage: 20,
    rating: 4.9,
    reviewCount: 440,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&q=80',
    description: 'A 75% layout tactile wireless mechanical keyboard featuring Bluetooth 5.1 connection, Gateron G Pro switches, and multi-device cross-platform pairing.',
    specs: ['Hot-swappable Gateron Brown/Red Switches', 'Connects up to 3 devices via Bluetooth', '4000 mAh battery lasts up to 240 hours', 'Compatible with Mac, Windows, iOS & Android'],
    isTrending: true,
    isFeatured: false,
    stock: 35,
    badge: 'Pro Choice',
    colors: ['#334155', '#e2e8f0']
  },

  // --- FASHION (6) ---
  {
    name: 'Adidas Essentials Premium Cotton T-Shirt',
    category: 'Fashion',
    price: 999,
    originalPrice: 1999,
    discountedPrice: 999,
    discountPercentage: 50,
    rating: 4.6,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    description: 'A classic crewneck tee crafted from 100% sustainably sourced organic cotton. Designed for everyday streetwear comfort and relaxed fitting.',
    specs: ['100% Single Jersey Organic Cotton', 'Ribbed crewneck collar', 'Moisture-absorbing AEROREADY', 'Regular relaxed fit'],
    isTrending: false,
    isFeatured: true,
    stock: 60,
    badge: 'Essential',
    colors: ['#ffffff', '#1e293b', '#64748b']
  },
  {
    name: "Levi's 501 Original Fit Stretch Jeans",
    category: 'Fashion',
    price: 999,
    originalPrice: 2999,
    discountedPrice: 999,
    discountPercentage: 66,
    rating: 4.8,
    reviewCount: 654,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=800&q=80',
    description: 'The blueprint for every pair of jeans in existence since 1873. Featuring classic straight leg styling and iconic button fly.',
    specs: ['99% Cotton, 1% Elastane', 'Signature button fly', '5-pocket styling', 'Sits at natural waist'],
    isTrending: true,
    isFeatured: true,
    stock: 45,
    badge: 'Iconic',
    colors: ['#1d4ed8', '#1e293b']
  },
  {
    name: 'Nike Sportswear Tech Fleece Full-Zip Hoodie',
    category: 'Fashion',
    price: 6499,
    originalPrice: 8999,
    discountedPrice: 6499,
    discountPercentage: 28,
    rating: 4.8,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80',
    description: 'Lightweight warmth with modern tailored design. Crafted from lightweight fleece that is smooth on both sides for premium comfort.',
    specs: ['66% Cotton, 34% Polyester', 'Zippered sleeve pocket', '4-panel hood for streamlined look', 'Standard relaxed fit'],
    isTrending: true,
    isFeatured: true,
    stock: 35,
    badge: 'Trending',
    colors: ['#0f172a', '#94a3b8']
  },
  {
    name: 'Zara Relaxed Fit Oversized Linen Shirt',
    category: 'Fashion',
    price: 999,
    originalPrice: 2499,
    discountedPrice: 999,
    discountPercentage: 60,
    rating: 4.5,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    description: 'Breathable 100% natural linen shirt styled with camp collar and button-up front. Perfect for summer outings and beach vacations.',
    specs: ['100% European Linen', 'Camp collar button down', 'Curved hem', 'Machine washable'],
    isTrending: false,
    isFeatured: false,
    stock: 50,
    badge: 'Summer Collection',
    colors: ['#ffffff', '#fef3c7']
  },
  {
    name: 'Champion Reverse Weave Heavyweight Sweatshirt',
    category: 'Fashion',
    price: 1499,
    originalPrice: 2999,
    discountedPrice: 1499,
    discountPercentage: 50,
    rating: 4.7,
    reviewCount: 275,
    image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
    description: 'The original heavyweight crewneck sweater designed to resist vertical shrinkage with signature stretch side panels.',
    specs: ['12 oz. Heavyweight fleece', 'Signature rib side panels', 'Double-needle construction', 'Classic C patch logo'],
    isTrending: false,
    isFeatured: false,
    stock: 40,
    badge: 'Classic',
    colors: ['#475569', '#0f172a']
  },
  {
    name: 'Calvin Klein Classic Trucker Denim Jacket',
    category: 'Fashion',
    price: 5999,
    originalPrice: 8999,
    discountedPrice: 5999,
    discountPercentage: 33,
    rating: 4.6,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=800&q=80',
    description: 'Timeless denim trucker jacket featuring metal button closures, dual chest flap pockets, and washed indigo finish.',
    specs: ['100% Rigid Denim Cotton', 'Metal button placket', 'Adjustable button waist tabs', 'Embossed CK leather patch'],
    isTrending: true,
    isFeatured: false,
    stock: 30,
    badge: 'Heritage',
    colors: ['#2563eb', '#1e293b']
  },

  // --- SHOES (6) ---
  {
    name: 'Nike Air Max 270 React Sneakers',
    category: 'Shoes',
    price: 8995,
    originalPrice: 12995,
    discountedPrice: 8995,
    discountPercentage: 30,
    rating: 4.7,
    reviewCount: 420,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    description: 'The Nike Air Max 270 delivers visible air under every step. Updated for modern comfort, it pays homage to the original 1991 Air Max 180.',
    specs: ['Max Air 270 unit delivers unrivaled comfort', 'Woven and synthetic fabric on upper', 'Phylon foam cushioning', 'Rubber outsole for traction'],
    isTrending: true,
    isFeatured: true,
    stock: 35,
    badge: 'Popular',
    colors: ['#ea580c', '#000000', '#ffffff']
  },
  {
    name: 'Nike Revolution 6 Lightweight Running Shoes',
    category: 'Shoes',
    price: 799,
    originalPrice: 2499,
    discountedPrice: 799,
    discountPercentage: 68,
    rating: 4.5,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80',
    description: 'Set the pace at the start of your running journey with the soft feel of the Nike Revolution 6. Made with at least 20% recycled content by weight.',
    specs: ['Soft foam midsole delivers smooth ride', 'Plush mesh placement along collar', 'Touch points at heel and tongue', 'Computer-generated outsole layout'],
    isTrending: false,
    isFeatured: true,
    stock: 50,
    badge: 'Eco Friendly',
    colors: ['#000000', '#dc2626', '#2563eb']
  },
  {
    name: 'Puma Velocity Nitro 2 Running Shoes',
    category: 'Shoes',
    price: 7499,
    originalPrice: 10999,
    discountedPrice: 7499,
    discountPercentage: 31,
    rating: 4.6,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    description: 'An all-in-one neutral running shoe for any distance. The Velocity Nitro 2 is a lightweight and responsive update to the NITRO family.',
    specs: ['NITRO FOAM advanced technology midsole', 'PUMAGRIP durable rubber compound', 'Engineered mesh upper for ventilation', 'Reflective accents for low light'],
    isTrending: false,
    isFeatured: false,
    stock: 40,
    badge: 'New',
    colors: ['#0284c7', '#000000']
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes',
    category: 'Shoes',
    price: 12999,
    originalPrice: 17999,
    discountedPrice: 12999,
    discountPercentage: 27,
    rating: 4.8,
    reviewCount: 390,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
    description: 'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole.',
    specs: ['Light BOOST generation foam', 'Linear Energy Push system', 'Continental™ Better Rubber outsole', 'Primeknit+ textile upper'],
    isTrending: true,
    isFeatured: true,
    stock: 30,
    badge: 'High Performance',
    colors: ['#ffffff', '#0f172a']
  },
  {
    name: 'Converse Chuck Taylor All Star High Top',
    category: 'Shoes',
    price: 999,
    originalPrice: 2499,
    discountedPrice: 999,
    discountPercentage: 60,
    rating: 4.9,
    reviewCount: 820,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    description: 'Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor.',
    specs: ['Lightweight durable canvas upper', 'Timeless high-top silhouette', 'Medial eyelets enhance airflow', 'Classic star ankle patch'],
    isTrending: true,
    isFeatured: false,
    stock: 60,
    badge: 'Iconic',
    colors: ['#000000', '#dc2626', '#ffffff']
  },
  {
    name: 'New Balance 574 Core Lifestyle Sneakers',
    category: 'Shoes',
    price: 5499,
    originalPrice: 7999,
    discountedPrice: 5499,
    discountPercentage: 31,
    rating: 4.7,
    reviewCount: 450,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80',
    description: 'Built to be a reliable shoe that could do many different things well, the 574 became an unpretentious classic staple for everyday wear.',
    specs: ['ENSEMBLE foam cushioning with EVA', 'Suede and mesh upper construction', 'Durable rubber outsole', 'Lightweight EVA foam midsole'],
    isTrending: false,
    isFeatured: false,
    stock: 40,
    badge: 'Best Value',
    colors: ['#64748b', '#0f172a']
  },

  // --- ACCESSORIES (6) ---
  {
    name: 'Herschel Little America Laptop Backpack (25L)',
    category: 'Accessories',
    price: 5499,
    originalPrice: 7999,
    discountedPrice: 5499,
    discountPercentage: 31,
    rating: 4.7,
    reviewCount: 231,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
    description: 'An iconic mountaineering-style backpack featuring a fleece-lined 15-inch laptop sleeve, drawcord closure, and rubber strap magnetic fastenings.',
    specs: ['Padded 15" fleece-lined laptop compartment', '25 Liter main storage capacity', 'Contoured shoulder straps with air mesh', 'Internal media pocket with headphone port'],
    isTrending: false,
    isFeatured: true,
    stock: 45,
    badge: 'New',
    colors: ['#334155', '#475569', '#15803d']
  },
  {
    name: 'Ray-Ban Classic Wayfarer Sunglasses (Polarized)',
    category: 'Accessories',
    price: 1999,
    originalPrice: 5999,
    discountedPrice: 1999,
    discountPercentage: 66,
    rating: 4.8,
    reviewCount: 472,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    description: 'Since 1952, Ray-Ban Wayfarer Classic has been a statement of style and individuality. Equipped with G-15 polarized crystal lenses for 100% UV protection.',
    specs: ['100% UV400 Protection & Polarized', 'Durable acetate frame in gloss black', 'Lens width: 50mm, Bridge: 22mm', 'Includes leather case and cleaning cloth'],
    isTrending: true,
    isFeatured: false,
    stock: 30,
    badge: 'Classics',
    colors: ['#0f172a', '#78350f']
  },
  {
    name: 'Leather Minimalist Slim Cardholder Wallet',
    category: 'Accessories',
    price: 799,
    originalPrice: 1999,
    discountedPrice: 799,
    discountPercentage: 60,
    rating: 4.8,
    reviewCount: 290,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&w=800&q=80',
    description: 'Handcrafted from full-grain Italian leather that ages gracefully over time. Holds up to 8 cards plus cash in a slim pocket-friendly form factor.',
    specs: ['100% Full Grain Tuscan Leather', 'RFID blocking security lining', 'Quick-access thumb slot', 'Ultra slim 0.28" thickness'],
    isTrending: true,
    isFeatured: false,
    stock: 50,
    badge: 'Slim Fit',
    colors: ['#78350f', '#0f172a', '#1e3a8a']
  },
  {
    name: 'Fossil The Minimalist Stainless Steel Watch',
    category: 'Accessories',
    price: 7495,
    originalPrice: 10995,
    discountedPrice: 7495,
    discountPercentage: 31,
    rating: 4.7,
    reviewCount: 215,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    description: 'Clean line design featuring slim stainless steel case, satin dial, and genuine brown leather strap with buckle closure.',
    specs: ['Quartz movement three-hand analog display', '44mm stainless steel case', 'Water resistant to 50m (165ft)', 'Interchangeable 22mm watch strap'],
    isTrending: false,
    isFeatured: true,
    stock: 25,
    badge: 'Elegance',
    colors: ['#78350f', '#0f172a']
  },
  {
    name: 'Bellroy Hide & Seek Premium Leather Wallet',
    category: 'Accessories',
    price: 4499,
    originalPrice: 6499,
    discountedPrice: 4499,
    discountPercentage: 30,
    rating: 4.9,
    reviewCount: 380,
    image: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    description: 'A traditional look with hidden features. Holds flat bills, cards, and includes a hidden coin pouch and card slot for extra security.',
    specs: ['Fits 5-12+ cards', 'Protected section for card privacy', 'Environmentally certified leather', 'Backed by 3-year warranty'],
    isTrending: true,
    isFeatured: false,
    stock: 40,
    badge: 'Top Pick',
    colors: ['#451a03', '#0f172a']
  },
  {
    name: 'Oakley Holbrook Matte Black Sunglasses',
    category: 'Accessories',
    price: 7990,
    originalPrice: 11290,
    discountedPrice: 7990,
    discountPercentage: 29,
    rating: 4.8,
    reviewCount: 260,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    description: 'Holbrook is a timeless, classic design fused with modern Oakley technology. Inspired by screen heroes from the 1940s, 50s, and 60s.',
    specs: ['Plutonite Lenses offer top UV Protection', 'Lightweight O Matter frame material', 'Prizm Lens Technology enhances color', '6 base lens geometry'],
    isTrending: false,
    isFeatured: false,
    stock: 35,
    badge: 'Sport Edition',
    colors: ['#0f172a', '#1e293b']
  },

  // --- BEAUTY (6) ---
  {
    name: 'Dyson Airwrap Multi-Styler Complete Long',
    category: 'Beauty',
    price: 45900,
    originalPrice: 49900,
    discountedPrice: 45900,
    discountPercentage: 8,
    rating: 4.9,
    reviewCount: 780,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    description: 'Curl, shape, smooth and hide flyaways using the Coanda effect with no extreme heat. Designed for multiple hair types and lengths.',
    specs: ['Powered by Dyson digital motor V9', 'Intelligent heat control prevents damage', 'Includes 6 re-engineered attachments', 'Storage case in Prussian Blue'],
    isTrending: true,
    isFeatured: true,
    stock: 20,
    badge: 'Luxury',
    colors: ['#1e1b4b', '#f43f5e']
  },
  {
    name: 'Estée Lauder Advanced Night Repair Serum (50ml)',
    category: 'Beauty',
    price: 7900,
    originalPrice: 10500,
    discountedPrice: 7900,
    discountPercentage: 25,
    rating: 4.8,
    reviewCount: 920,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1608248597263-0057e43a4524?auto=format&fit=crop&w=800&q=80',
    description: 'Harness the restorative power of night. Deeply hydrates and reduces multiple signs of aging caused by environmental assaults.',
    specs: ['72-hour hydration with Hyaluronic Acid', 'Chronolux™ Power Signal Technology', 'Oil-free, dermatologist tested', 'Suitable for all skin types'],
    isTrending: true,
    isFeatured: true,
    stock: 45,
    badge: 'Best Seller',
    colors: ['#78350f']
  },
  {
    name: 'CeraVe Hydrating Facial Cleanser (16 oz)',
    category: 'Beauty',
    price: 1099,
    originalPrice: 1499,
    discountedPrice: 1099,
    discountPercentage: 26,
    rating: 4.9,
    reviewCount: 1420,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80',
    description: 'Gentle moisturizing lotion cleanser formulated with 3 essential ceramides and hyaluronic acid to cleanse without stripping moisture.',
    specs: ['Formulated with Ceramides 1, 3, 6-II', 'Non-comedogenic & fragrance free', 'MVE Technology for 24-hr hydration', 'Accepted by National Eczema Association'],
    isTrending: false,
    isFeatured: false,
    stock: 80,
    badge: 'Dermatologist Recommended',
    colors: ['#0284c7']
  },
  {
    name: 'Olaplex No.3 Hair Perfector Repairing Treatment',
    category: 'Beauty',
    price: 2200,
    originalPrice: 2950,
    discountedPrice: 2200,
    discountPercentage: 25,
    rating: 4.8,
    reviewCount: 1100,
    image: 'https://images.unsplash.com/photo-1608248597263-0057e43a4524?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    description: 'An at-home weekly treatment that reduces breakage and visibly strengthens hair, improving its look and feel.',
    specs: ['Relinks broken disulfide bonds', 'Restores hair structure and texture', 'Sulfate-free, Paraben-free, Vegan', 'For all hair types'],
    isTrending: true,
    isFeatured: false,
    stock: 60,
    badge: 'Cult Favorite',
    colors: ['#ffffff']
  },
  {
    name: 'Laneige Lip Sleeping Mask (Berry 20g)',
    category: 'Beauty',
    price: 1350,
    originalPrice: 1750,
    discountedPrice: 1350,
    discountPercentage: 22,
    rating: 4.9,
    reviewCount: 1350,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    description: 'A leave-on lip mask that delivers intense moisture and antioxidants while you sleep with Berry Fruit Complex and Vitamin C.',
    specs: ['Berry Fruit Complex™ & Vitamin C', 'Moisture Wrap™ technology', 'Smooths flaky dry lips overnight', 'Includes spatual applicator'],
    isTrending: true,
    isFeatured: false,
    stock: 70,
    badge: 'Award Winner',
    colors: ['#f43f5e']
  },
  {
    name: 'Glossier Boy Brow Fluffing Hair Pomade',
    category: 'Beauty',
    price: 1400,
    originalPrice: 1800,
    discountedPrice: 1400,
    discountPercentage: 22,
    rating: 4.7,
    reviewCount: 680,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    description: 'A brushable, creamy brow pomade that visibly thickens, shapes, and grooms brows into place for long-lasting flexible hold.',
    specs: ['Inspired by traditional hair pomade', 'Soft flexible hold without stiffening', 'Conditioning Oleic Acid & Lecithin', 'Alcohol-free and Cruelty-free'],
    isTrending: false,
    isFeatured: false,
    stock: 50,
    badge: 'Must Have',
    colors: ['#78350f', '#0f172a']
  },

  // --- HOME (6) ---
  {
    name: 'Minimalist Ceramic Table Lamp with Linen Shade',
    category: 'Home',
    price: 4999,
    originalPrice: 6999,
    discountedPrice: 4999,
    discountPercentage: 28,
    rating: 4.7,
    reviewCount: 145,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=800&q=80',
    description: 'Bring warm ambient light into your living space. Handcrafted ceramic base with subtle textured matte glaze paired with natural oatmeal linen.',
    specs: ['Handcrafted matte ceramic base', '100% natural textured linen shade', '3-way dimmable touch sensor', 'Standard E26 LED warm light bulb included'],
    isTrending: false,
    isFeatured: false,
    stock: 35,
    badge: 'Handcrafted',
    colors: ['#f5f5f4', '#d6d3d1']
  },
  {
    name: 'Nespresso Vertuo Pop Coffee Machine by DeLonghi',
    category: 'Home',
    price: 11999,
    originalPrice: 16999,
    discountedPrice: 11999,
    discountPercentage: 29,
    rating: 4.8,
    reviewCount: 410,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    description: 'Compact and colorful espresso maker delivering 5 cup sizes at the touch of a button using Centrifusion™ extraction technology.',
    specs: ['Centrifusion™ barcode reading tech', 'Fast 30-second heat up', 'Brews 5 cup sizes (1.35oz to 18oz)', 'Made from 35% recycled plastic'],
    isTrending: true,
    isFeatured: true,
    stock: 30,
    badge: 'Popular',
    colors: ['#dc2626', '#0f172a', '#f59e0b']
  },
  {
    name: 'Philips Hue Smart Ambient Starter Kit (4 Bulbs)',
    category: 'Home',
    price: 10999,
    originalPrice: 14999,
    discountedPrice: 10999,
    discountPercentage: 26,
    rating: 4.9,
    reviewCount: 320,
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    description: 'Transform your home lighting with 16 million colors. Kit includes Hue Bridge and 4 smart E26 color bulbs compatible with Alexa and Google Assistant.',
    specs: ['16 million colors + warm-to-cool white', 'Includes Hue Bridge for smart control', 'Voice control with Alexa, Siri, Google', 'Set timers, schedules, and automation'],
    isTrending: true,
    isFeatured: true,
    stock: 25,
    badge: 'Smart Home',
    colors: ['#0f172a']
  },
  {
    name: 'Ember Temperature Control Smart Mug 2 (14 oz)',
    category: 'Home',
    price: 9990,
    originalPrice: 12990,
    discountedPrice: 9990,
    discountPercentage: 23,
    rating: 4.7,
    reviewCount: 290,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?auto=format&fit=crop&w=800&q=80',
    description: 'Designed for home or office, Ember Mug 2 allows you to set your exact drinking temperature and keeps it there for up to 80 minutes.',
    specs: ['Maintains set temp between 120°F - 145°F', '1.5-hour battery life (all day on coaster)', 'Smart LED indicator & Auto-sleep mode', 'Hand wash safe with IPX7 rating'],
    isTrending: false,
    isFeatured: false,
    stock: 35,
    badge: 'Innovator',
    colors: ['#000000', '#ffffff']
  },
  {
    name: 'Le Creuset Enameled Cast Iron Dutch Oven (5.5 qt)',
    category: 'Home',
    price: 26900,
    originalPrice: 32900,
    discountedPrice: 26900,
    discountPercentage: 18,
    rating: 4.9,
    reviewCount: 560,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    description: 'An indispensable kitchen classic. Legendary cast iron provides superior heat retention and distribution for slow cooking, roasting, and searing.',
    specs: ['Enameled cast iron resists dulling & chipping', 'Oven-safe up to 500°F', 'Light-colored interior for monitoring cooking', 'Compatible with all cooktops including induction'],
    isTrending: true,
    isFeatured: true,
    stock: 20,
    badge: 'Chef Choice',
    colors: ['#dc2626', '#0f172a', '#ea580c']
  },
  {
    name: 'KitchenAid Artisan Series 5-Quart Stand Mixer',
    category: 'Home',
    price: 32900,
    originalPrice: 39900,
    discountedPrice: 32900,
    discountPercentage: 17,
    rating: 4.9,
    reviewCount: 840,
    image: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=80',
    secondaryImage: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    description: 'Make up to 9 dozen cookies in a single batch with the KitchenAid Artisan tilt-head stand mixer featuring 10 speeds and 5-quart stainless bowl.',
    specs: ['5-Quart stainless steel bowl with handle', '10 speed slide control', 'Includes flat beater, dough hook & wire whip', '59-point planetary mixing action'],
    isTrending: true,
    isFeatured: false,
    stock: 25,
    badge: 'Iconic Kitchen',
    colors: ['#dc2626', '#0f172a', '#e2e8f0']
  }
];

export const seedDatabase = async () => {
  try {
    console.log('Checking and seeding database collections...');
    await Product.deleteMany();
    await User.deleteMany();

    console.log('Inserting seed users...');
    const adminUser = await User.create({
      name: 'Admin User',
      email: 'admin@luxestore.com',
      password: 'admin123password',
      role: 'admin'
    });

    const demoUser = await User.create({
      name: 'Demo Customer',
      email: 'user@luxestore.com',
      password: 'user123password',
      role: 'user'
    });

    console.log(`Users created: Admin (${adminUser.email}), User (${demoUser.email})`);

    console.log('Inserting seed products...');
    const createdProducts = await Product.insertMany(products);
    console.log(`Successfully seeded ${createdProducts.length} products into MongoDB!`);
    return { adminUser, demoUser, count: createdProducts.length };
  } catch (error) {
    console.error(`Seeding error: ${error.message}`);
    throw error;
  }
};

const runStandalone = async () => {
  try {
    await connectDB();
    await seedDatabase();
    console.log('\nData Seeding Completed Successfully!');
    process.exit(0);
  } catch (err) {
    process.exit(1);
  }
};

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('seeder.js')) {
  runStandalone();
}
